#!/bin/sh
# Generate src/embedded_slots.h: fixed-width base64 credential slots that can be
# swapped in the finished binary with sed, no recompile.
#
#   ./gen_cred_slots.sh [src_dir]
#
# Each slot is one line: a unique begin marker, DBCRED_SLOT_WIDTH bytes of
# base64 right-padded with '.' (not a base64 character, so the reader stops at
# the first one), then a matching end marker. Markers are all the same length,
# so the reader can skip a constant prefix. Because the width never changes, the
# region can be overwritten in place without changing the file size — which is
# what lets a plain sed patch it without breaking the ELF.
set -eu
SRC="${1:-/home/q/ssh/dropbear-2026.94}"
OUT="$SRC/src/embedded_slots.h"

# Wide enough for a base64-encoded RSA-4096 Dropbear private key (~2.5 kB).
WIDTH=2800

# One line of WIDTH '.' characters, the empty-slot placeholder.
pad="$(awk -v w="$WIDTH" 'BEGIN{s="";for(i=0;i<w;i++)s=s".";print s}')"

emit_slot() { # $1 = id (exactly 2 chars)
	printf 'static volatile const char dbcred_%s_slot[] __attribute__((used, aligned(16))) =\n' "$1"
	printf '\t"@@DBCRED:%s:B@@"\n' "$1"
	printf '\t"%s"\n' "$pad"
	printf '\t"@@DBCRED:%s:E@@";\n\n' "$1"
}

{
	cat <<'HDR'
/* embedded_slots.h - GENERATED by gen_cred_slots.sh. Do not edit by hand.
 *
 * Runtime-patchable credential slots. Each slot holds base64 text between two
 * unique markers, padded with '.' to a fixed width so the region can be
 * rewritten in the finished binary (same length => ELF stays valid) with:
 *
 *   sed "s|@@DBCRED:id:B@@[^@]*@@DBCRED:id:E@@|@@DBCRED:id:B@@<PADDED_B64>@@DBCRED:id:E@@|"
 *
 * where <PADDED_B64> is the new key's base64 right-padded with '.' to the
 * original width. The patch-cred helper does the padding for you.
 *
 * The arrays are volatile so the reader always loads the bytes actually present
 * in .rodata (i.e. whatever was patched), never a compile-time copy. */
#ifndef DROPBEAR_EMBEDDED_SLOTS_H
#define DROPBEAR_EMBEDDED_SLOTS_H
#ifdef DROPBEAR_USE_EMBEDDED_CREDS

HDR
	printf '#define DBCRED_SLOT_WIDTH %s\n' "$WIDTH"
	printf '#define DBCRED_MARKER_LEN 15  /* strlen("@@DBCRED:xx:B@@") */\n\n'
	printf '/* Defined in cli-runopts.c, used before its definition in that file. */\n'
	printf 'void load_embedded_identity(void);\n\n'
	emit_slot id
	emit_slot hk
	emit_slot ak
	cat <<'RDR'
/* Decode a slot into a freshly malloc'd buffer. Returns NULL and sets *outlen
 * to 0 for an unpatched (all-'.') slot. Caller frees. */
static inline unsigned char *dbcred_slot_get(const volatile char *slot,
		unsigned int *outlen) {
	const volatile char *p = slot + DBCRED_MARKER_LEN;
	unsigned char *b64;
	unsigned char *out;
	unsigned long declen;
	unsigned int n = 0;

	/* base64 payload runs until the padding '.' or the end marker '@'. */
	while (n < DBCRED_SLOT_WIDTH && p[n] != '.' && p[n] != '@' && p[n] != '\0') {
		n++;
	}
	if (n == 0) {
		*outlen = 0;
		return NULL;
	}

	/* Copy out of the volatile array before handing it to base64_decode. */
	b64 = m_malloc(n);
	{
		unsigned int i;
		for (i = 0; i < n; i++) {
			b64[i] = (unsigned char)p[i];
		}
	}

	declen = n; /* decoded length is always <= encoded length */
	out = m_malloc(declen);
	if (base64_decode(b64, n, out, &declen) != CRYPT_OK) {
		m_free(b64);
		m_free(out);
		*outlen = 0;
		return NULL;
	}
	m_free(b64);
	*outlen = (unsigned int)declen;
	return out;
}

#endif /* DROPBEAR_USE_EMBEDDED_CREDS */
#endif /* DROPBEAR_EMBEDDED_SLOTS_H */
RDR
} > "$OUT"
echo "wrote $OUT (width $WIDTH)"
